# Generated by Django 3.0.3 on 2020-03-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marinerdocument',
            name='drug_test_compliant',
            field=models.BooleanField(default=False),
        ),
    ]
