# Generated by Django 3.0.3 on 2020-03-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatime', '0002_auto_20200301_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='marinerprofile',
            name='first_name',
            field=models.CharField(default='Josh', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marinerprofile',
            name='last_name',
            field=models.CharField(default='Williamson', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marinerprofile',
            name='middle_name',
            field=models.CharField(default='Samson', max_length=255),
            preserve_default=False,
        ),
    ]
