# Generated by Django 3.0.3 on 2020-03-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatime', '0003_auto_20200320_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marinerprofile',
            name='mariner_ref_num',
        ),
        migrations.AddField(
            model_name='marinerdocument',
            name='mariner_ref_num',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marinerdocument',
            name='advanced_fire_expr_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='marinerdocument',
            name='basic_training_expr_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='marinerdocument',
            name='first_aid_cpr_expr_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='marinerdocument',
            name='med_ntl_expr_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='marinerdocument',
            name='med_pilot_expr_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='marinerdocument',
            name='med_stcw_expr_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='marinerdocument',
            name='mmc_doc_num',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marinerdocument',
            name='mmc_expr_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='marinerdocument',
            name='mmc_issue_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='marinerdocument',
            name='passport_expr_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='marinerdocument',
            name='twic_expr_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='marinerprofile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='marinerprofile',
            name='citizenship_cntry',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marinerprofile',
            name='residence_state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
