# Generated by Django 3.0.3 on 2020-04-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatime', '0004_auto_20200325_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marinerprofile',
            name='middle_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
