# Generated by Django 3.0.3 on 2020-04-18 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatime', '0005_auto_20200418_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marinerprofile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 4, 18)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marinerprofile',
            name='citizenship_cntry',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marinerprofile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marinerprofile',
            name='residence_state',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
