# Generated by Django 3.0.7 on 2020-06-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seatime', '0006_auto_20200418_1414'),
    ]

    operations = [
    ]
