# Generated by Django 3.0.7 on 2020-06-30 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seatime', '0007_auto_20200630_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='propulsion',
        ),
        migrations.RemoveField(
            model_name='vessel',
            name='tonnage',
        ),
    ]
