# Generated by Django 3.0.7 on 2020-07-02 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seatime', '0008_auto_20200630_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffposition',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staffposition',
            name='rank',
        ),
    ]
