# Generated by Django 3.0.7 on 2020-07-17 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seatime', '0011_auto_20200702_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffratingcombinations',
            name='position_rating',
        ),
        migrations.AddField(
            model_name='staffratingcombinations',
            name='position_rating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seatime.Rating'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='staffratingcombinations',
            name='staff_position',
        ),
        migrations.AddField(
            model_name='staffratingcombinations',
            name='staff_position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seatime.StaffPosition'),
            preserve_default=False,
        ),
    ]
