# Generated by Django 3.0.7 on 2020-07-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seatime', '0012_auto_20200717_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffratingcombinations',
            name='position_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='seatime.Rating'),
        ),
        migrations.AlterField(
            model_name='staffratingcombinations',
            name='staff_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='seatime.StaffPosition'),
        ),
    ]
