# Generated by Django 3.0.7 on 2020-07-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatime', '0014_album_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffratingcombinations',
            name='position_rating',
        ),
        migrations.RemoveField(
            model_name='staffratingcombinations',
            name='staff_position',
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.AddField(
            model_name='staffposition',
            name='ratings',
            field=models.ManyToManyField(to='seatime.Rating'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='StaffRatingCombinations',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
