# Generated by Django 3.0.7 on 2020-07-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatime', '0015_auto_20200720_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('tag', models.ManyToManyField(to='seatime.Tag')),
            ],
        ),
    ]
